SELECT TOP (1000) [ID]
      ,[NamaPenumpang]
      ,[TanggalKeberangkatan]
      ,[StasiunAsal]
      ,[StasiunTujuan]
      ,[Kelas]
      ,[JumlahPenumpang]
  FROM [tiketkeretaapi].[dbo].[PemesananTiket]
